[package]
name = "flatline-umac"
version = "0.1.0"
edition = "2024"
authors = ["holdxen"]
description = "Rust bindings for UMAC (Universal Message Authentication Code)"
license = "MIT"
repository = "https://github.com/holdxen/flatline-umac"
keywords = ["umac", "mac", "cryptography", "authentication", "ffi"]
categories = ["cryptography", "api-bindings"]
readme = "README.md"

[dependencies]

[build-dependencies]
bindgen = "0.72.1"
cc = "1.2.65"
